services:
  frontend:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

  backend:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    env_file: .env
    environment:
      - OLLAMA_HOST=http://ollama:11434
      # Aqui eu passo as variáveis de ambiente pro Django saber exatamente onde achar o Postgres dentro do Docker
      - DB_NAME=ai4po_db
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_HOST=db  # O host é 'db' porque é o nome do container do banco na mesma rede Docker
      - DB_PORT=5432
    depends_on:
      - db      # Faço o backend esperar o container do banco subir antes de iniciar
      - ollama

  # BANCO DE DADOS POSTGRESQL COM PGVECTOR
  # Aqui eu configuro o PostgreSQL usando a imagem com suporte nativo à extensão pgvector,
  # que é fundamental para salvar os embeddings (vetores) e rodar as buscas semânticas da IA.
  db:
    image: pgvector/pgvector:pg16
    container_name: ai4po_db
    restart: always
    environment:
      POSTGRES_DB: ai4po_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"  # Exponho a porta 5432 para conseguir conectar via DBeaver/psql ou rodar comandos locais
    volumes:
      - pgdata:/var/lib/postgresql/data  # Garante que os dados e tabelas não sumam quando o container reiniciar

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  # PARTE DE CONFIGURAR A AUTOMAÇÃO DO MODELO (INICIAR COM O DOCKER COMPOSE)
  # ollama-pull:
  #   image: ollama/ollama:latest
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   entrypoint: ["/bin/sh", "-c"]
  #   command: >
  #     "ollama serve & sleep 3 && ollama pull qwen3.5:4b && echo 'modelo pronto'"
  #   depends_on:
  #     - ollama

volumes:
  ollama_data:
  # Volume dedicado para persistir todos os dados do banco relacional e os vetores do pgvector
  pgdata: