services:
  frontend:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend

  backend:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      # Aqui eu passo as variáveis de ambiente pro Django saber exatamente onde achar o Postgres dentro do Docker
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      # Ollama roda fora do Docker (na máquina), então o container acessa pelo host
      - OLLAMA_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL= ai4po-model
