services:
  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

  backend:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    env_file: .env
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - db

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  # PARTE DE CONFIGURAR A AUTOMAÇÃO DO MODELO (INICIAR COM O DOCKER COMPOSE)
  # ollama-pull:
  #   image: ollama/ollama:latest
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   entrypoint: ["/bin/sh", "-c"]
  #   command: >
  #     "ollama serve & sleep 3 && ollama pull qwen3.5:4b && echo 'modelo pronto'"
  #   depends_on:
  #     - ollama

volumes:
  ollama_data:
  postgres_data: