# Generated by Django 6.1.1 on 2026-09-20 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='objetivo',
        ),
        migrations.AddField(
            model_name='projeto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 20, 19, 8, 50, 718971, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Inativo', 'Inativo'), ('Ativo', 'Ativo')], default='Rascunho', max_length=20),
        ),
    ]
