# Generated by Django 6.1.1 on 2026-09-21 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='objetivo',
        ),
        migrations.AddField(
            model_name='projeto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Inativo', 'Inativo'), ('Ativo', 'Ativo')], default='Rascunho', max_length=20),
        ),
    ]
