# Generated by Django 6.1.1 on 2026-09-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_documento_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('processado', 'Processado'), ('erro', 'Erro')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='mensagem_erro',
            field=models.TextField(blank=True, default=''),
        ),
    ]
