# Generated by Django 6.1.1 on 2026-09-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_status_titulo_criado_em'),
        ('projects', '0004_documento_estado_documento_mensagem_erro'),
    ]

    operations = [
    ]
