# Generated by Django 6.1.1 on 2026-09-15 23:48

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='ChunkIndexado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('caminho_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('indice', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('documento_caminho', models.CharField(max_length=255)),
                ('projeto', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['documento_caminho', 'indice'],
            },
        ),
    ]
