# Generated by Django 6.1.1 on 2026-09-13 23:28

import django.db.models.deletion
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0002_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkdoc',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='projects.documento'),
        ),
        migrations.AddField(
            model_name='chunkdoc',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='projects.projeto'),
        ),
        migrations.AddIndex(
            model_name='chunkdoc',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_vector_cosine_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
