# Generated by Django 6.1.1 on 2026-09-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('objetivo', models.TextField()),
                ('escopo_macro', models.TextField()),
                ('resultado', models.TextField()),
                ('criterios_de_aceitacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('objetivo', models.TextField()),
                ('criterios_de_aceitacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('user_story', models.TextField()),
                ('criterio_de_aceitacao', models.TextField()),
                ('regras_observacoes', models.TextField()),
            ],
        ),
    ]
