# Generated by Django 6.1.1 on 2026-09-13 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backlog', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epico',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epicos', to='projects.projeto'),
        ),
        migrations.AddField(
            model_name='feature',
            name='epico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='backlog.epico'),
        ),
        migrations.AddField(
            model_name='pbi',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pbis', to='backlog.feature'),
        ),
    ]
