# Generated by Django 6.1.1 on 2026-09-21 00:31

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pbi',
            old_name='user_story',
            new_name='userstory_paraque',
        ),
        migrations.AddField(
            model_name='epico',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pbi',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pbi',
            name='userstory_como',
            field=models.CharField(default=datetime.datetime(2026, 9, 21, 0, 31, 21, 899271, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pbi',
            name='userstory_quero',
            field=models.TextField(default=datetime.datetime(2026, 9, 21, 0, 31, 34, 320419, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='epico',
            name='criterios_de_aceitacao',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='epico',
            name='escopo_macro',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='feature',
            name='criterios_de_aceitacao',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='regras_observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dado', models.TextField()),
                ('quando', models.TextField()),
                ('entao', models.TextField()),
                ('pbi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cenarios', to='backlog.pbi')),
            ],
        ),
    ]
